### ISSUE TITLE
client secure_auth enabled

### ISSUE THREAD

**Issue by rodrigo-fagundes** [datamapper/dm-mysql-adapter#4]
I'm trying to connect to a mysql 5.6 database and get this error: client secure_auth enabled. I tried to set OLD_PASSWORD('password') to the user, but it didn't work. Also tried with no success to set :secure_auth => false in the setup options.

Did anyone face this problem? Am I missing something?

**Comment by basex** [comment]
I load the following way:

``` ruby
DataMapper.setup(:default, YAML.load(ERB.new(File.read('config/database.yml')).result)[RACK_ENV])
```

and inside the yml

``` yml
development: &defaults
  adapter: mysql
  encoding: UTF-8
  database: test
  username: test
  password: test
  host: 127.0.0.1
```
